import type { Metadata } from "next";
import "./globals.css";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";
import AuthSession from "@/components/AuthSession"; // To display session status and sign-out

export const metadata: Metadata = {
  title: "Next.js 15 App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>
          <header style={{ padding: "1rem", borderBottom: "1px solid #ccc" }}>
            <AuthSession />
          </header>
          <main>{children}</main>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
